### PR TITLE
Microverse Portfolio: contact me section

### PR DESCRIPTION
**Pull request by joa-byte**
## Microverse Portfolio: contact me section

in this branch I've: 
- uploaded the final section of the portfolio.
- created a division for the contact me part and the social media logos in the index.
- added the final changes needed in the style sheet.
- uploaded a screenshot of the final result for the readme file to show.

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid PR :red_circle: :rotating_light:

### Your Summary

first review summary

### Descriptive Summary
clinton summary


You have not made your summary descriptive. Please make it more descriptive something like in above image. :+1:

### Your Project
project

### Figma Template

Figma

- [ ] Your project is not following the Figma template. The majority of your project requirements are not fulfilled. Please fulfill all the requirements and then resubmit your project :+1:

**_This will not be counted as a review because it is invalidated by me. So, kindly make the above changes in your project and submit it for review. :blush:_**

**Review by Ugboaja-Uchechi — CHANGES_REQUESTED** [review]
Hi @joa-byte , 

## Status: Changes Required

Good job so far! 👏 . Your design looks really good 👍 . There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Repo looks professional
- Pull request has a good description
- Linters are passing ✔️ 


## Required Changes ♻️

- [ ] Please change the `div` with a `class of tool-bar` to a `nav` tag so it can be more semantic. You can read more about semantic HTML in this [article](https://www.w3schools.com/html/html5_semantic_elements.asp) 🙏 .
- [ ] Please change the `h3` with a `class of my-logo` to an `a` tag so it can be more semantic. You can read more about semantic HTML in this [article](https://www.w3schools.com/html/html5_semantic_elements.asp) 🙏 .

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mwanawabangona — CHANGES_REQUESTED** [review]
## Status: Changes Required

 ## Hello there @joa-byte  👋🏽

###  You have done an amazing job so far! 👏🏽 👏🏽


There are some issues that you still need to work on to go to the next project but you are almost there! pinching_hand


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional briefcase
* ✅  Solid pull request scroll🧐
* ✅  Good quality commits

## Required Changes
 _**Check the comments under the review.**_

 ## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @mwanawabangona in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mwanawabangona — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @joa-byte 👋,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @mwanawabangona in your question so I can receive the notification.

**Pull request merged**
